apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-helloworldsvc-deployment
spec:
  selector:
    matchLabels:
      app: dotnet-helloworldsvc
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: dotnet-helloworldsvc
    spec:
      containers:
      - name: dotnet-helloworldsvc
        image: daed.duckdns.org:50000/dotnet-helloworld-service:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dotnet-helloworldsvc
  name: dotnet-helloworldsvc
spec:
    ports:
    - nodePort: 30680
      port: 80
      protocol: TCP
      targetPort: 80
    selector: 
      app: dotnet-helloworldsvc
    type: NodePort
